
from fastapi import APIRouter, Depends, HTTPException, Header
from fastapi.responses import StreamingResponse, JSONResponse
from sqlalchemy.orm import Session
import requests
from datetime import datetime
import os
import logging
from typing import Any, Dict, Optional

from app.schemas import execution_method_schema
from app.crud.execution_method_crud import (
    get_service_by_workflow_id,
    log_genrocket_service_execution
)
from app.database import get_db

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

router = APIRouter(tags=["GenRocket Execution"])

# ------------------------- Constants ---------------------------------------

SUPPORTED_EXTS = {".csv", ".xlsx", ".xls"}  # add others only if needed
# NOTE: Requirement explicitly calls out Excel; CSV is commonly generated by GenRocket.
# .xml should be rejected as "Unsupported File format".

# ------------------------- Helpers -----------------------------------------

def _find_first_string_in_nested(obj: Any) -> Optional[str]:
    """Safely search any nested dict/list for the first string (e.g., a filename)."""
    if isinstance(obj, str):
        return obj
    if isinstance(obj, dict):
        for v in obj.values():
            found = _find_first_string_in_nested(v)
            if found:
                return found
    if isinstance(obj, list):
        for v in obj:
            found = _find_first_string_in_nested(v)
            if found:
                return found
    return None

def _safe_parse_json(response: requests.Response) -> Dict[str, Any]:
    """
    Parse JSON body safely. If GenRocket returns non-JSON (often caused by corrupted .grs),
    raise a descriptive error instead of triggering 500s.
    """
    try:
        return response.json()
    except ValueError as e:
        # Non-JSON body from GenRocket → treat as corrupted scenario / invalid file
        raise HTTPException(status_code=400, detail="The GenRocket file is not correct") from e

def _extract_filename(response_json: Dict[str, Any], scenario_name: str) -> Optional[str]:
    """
    Attempt to extract a filename from GenRocket response in a robust way.

    Expected patterns:
        response_json["fileNameStore"][<scenario>][<Receiver>][0] -> "file.ext"
    We avoid hardcoding Receiver names and fall back to scanning.
    """
    try:
        file_store = response_json.get("fileNameStore", {})
        scenario_block = file_store.get(scenario_name)
        if scenario_block:
            if isinstance(scenario_block, dict):
                for _receiver_name, maybe_list in scenario_block.items():
                    if isinstance(maybe_list, list) and maybe_list:
                        if isinstance(maybe_list[0], str):
                            return maybe_list[0]
                        found = _find_first_string_in_nested(maybe_list)
                        if found:
                            return found
                    # generic deep scan
                    found = _find_first_string_in_nested(maybe_list)
                    if found:
                        return found
            # still try to scan even if not dict
            found = _find_first_string_in_nested(scenario_block)
            if found:
                return found
    except Exception as e:
        logger.warning(f"Filename extraction (scenario path) failed: {e}")

    # Fallback: scan entire fileNameStore
    try:
        file_store = response_json.get("fileNameStore")
        if file_store:
            found = _find_first_string_in_nested(file_store)
            if found:
                return found
    except Exception as e:
        logger.warning(f"Filename extraction (global fileNameStore) failed: {e}")

    # Ultimate fallback: scan full response
    return _find_first_string_in_nested(response_json)

def _validate_filename_or_raise(file_name: Optional[str]) -> str:
    """
    Validate presence and supported extension of file_name.
    Raises HTTPException with:
      - 400 "File Name not found"
      - 415 "Unsupported File format"
    """
    if not file_name or not isinstance(file_name, str) or file_name.strip() == "":
        raise HTTPException(status_code=400, detail="File Name not found")

    # Normalize and check extension
    _, ext = os.path.splitext(file_name.strip().lower())

    if ext == ".xml":
        # Explicit requirement
        raise HTTPException(status_code=415, detail="Unsupported File format")

    if ext not in SUPPORTED_EXTS:
        # Generic unsupported extension
        raise HTTPException(status_code=415, detail="Unsupported File format")

    return file_name.strip()

def _guess_mime_type(filename: str) -> str:
    """Return an appropriate Content-Type from the file extension."""
    ext = os.path.splitext(filename.lower())[1]
    if ext == ".csv":
        return "text/csv"
    if ext == ".xlsx":
        return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    if ext == ".xls":
        return "application/vnd.ms-excel"
    # fallback
    return "application/octet-stream"

def get_file_path(base_path: str, file_name: str | None) -> Optional[str]:
    """Search the base path and subdirectories for the given file_name."""
    if not file_name:
        return None

    # direct children
    try:
        for item in os.listdir(base_path):
            item_path = os.path.join(base_path, item)
            if os.path.isfile(item_path) and item == file_name:
                return item_path
    except Exception as e:
        logger.warning(f"Base path listing failed: {e}")

    # recursive search
    for root, _dirs, files in os.walk(base_path):
        if file_name in files:
            return os.path.join(root, file_name)

    return None

def _log_and_return_json_failure(
    db: Session,
    service,
    workflow_id: int,
    start_time: datetime,
    end_time: datetime,
    runtime,
    status_message: str,
    output_json: Dict[str, Any] | str,
    http_status: int,
) -> JSONResponse:
    """Utility to log FAILED status and return JSON error consistently."""
    log_genrocket_service_execution(
        db=db,
        tool_id=service.tool_id,
        tool_name="GenRocket",
        workflow_id=workflow_id,
        start_time=start_time,
        end_time=end_time,
        runtime=runtime,
        created_by=service.username,
        status="FAILED",
        output_json=str(output_json),
    )
    return JSONResponse(status_code=http_status, content={"code": str(http_status), "message": status_message})

# --------------------- Streaming endpoint (download) ------------------------

@router.post("/execute-genrocket-service/{workflow_id}")
def execute_genrocket_service(
    workflow_id: int,
    x_user_id: str = Header(..., description="User ID for authentication"),
    db: Session = Depends(get_db),
):
    """
    Executes the workflow via GenRocket and streams the resulting file on success.
    Returns:
      - 404: Service/workflow not found or file not found
      - 400: Scenario failed / corrupted .grs / missing filename
      - 415: Unsupported File format (e.g., .xml)
      - 200: Streaming file with Content-Disposition header
    """
    logger.info(f"Starting GenRocket execution for workflow_id={workflow_id}")

    # Fetch service details
    service = get_service_by_workflow_id(db, workflow_id)
    if not service:
        raise HTTPException(status_code=404, detail="Service not found")

    # Prepare payload
    payload = execution_method_schema.Genrocket_mirror_payload(
        username=service.username,
        password=service.password,
        clientAppId=service.clientappid,
        clientUserId=service.clientuserid,
        scenario=service.scenario,
        scenarioPath=service.scenariopath,
        keepFileName=service.keepfilename
    ).dict()

    # Execute and time it
    start_time = datetime.utcnow()
    try:
        response = requests.post(
            "http://10.100.242.133:8088/rest/scenario",
            json=payload,
            timeout=600
        )
        response.raise_for_status()
        try:
            response_json = _safe_parse_json(response)
        except HTTPException as he:
            # Corrupted .grs / invalid response
            return _log_and_return_json_failure(
                db=db,
                service=service,
                workflow_id=workflow_id,
                start_time=start_time,
                end_time=datetime.utcnow(),
                runtime=datetime.utcnow() - start_time,
                status_message=he.detail,  # "The GenRocket file is not correct"
                output_json={"payload": payload, "error": he.detail},
                http_status=400,
            )
        status = "SUCCESS"
        logger.info(f"GenRocket API response parsed successfully")
    except requests.exceptions.RequestException as e:
        status = "FAILED"
        response_json = {"error": str(e)}
        logger.error(f"GenRocket API call failed: {e}")

    end_time = datetime.utcnow()
    runtime = end_time - start_time

    # If HTTP call failed
    if status != "SUCCESS":
        return _log_and_return_json_failure(
            db=db,
            service=service,
            workflow_id=workflow_id,
            start_time=start_time,
            end_time=end_time,
            runtime=runtime,
            status_message="Scenario Failed",
            output_json=response_json,
            http_status=400,
        )

    # Extract and validate filename
    scenario_name = service.scenario or ""
    raw_file_name = _extract_filename(response_json, scenario_name)
    try:
        file_name = _validate_filename_or_raise(raw_file_name)
    except HTTPException as he:
        # Missing filename or unsupported format
        return _log_and_return_json_failure(
            db=db,
            service=service,
            workflow_id=workflow_id,
            start_time=start_time,
            end_time=end_time,
            runtime=runtime,
            status_message=he.detail,  # "File Name not found" or "Unsupported File format"
            output_json={"payload": payload, "response": response_json},
            http_status=he.status_code,
        )

    # Resolve full path
    base_path = r"C:\Shared_Folder\02 Tools\Genrocket Output"
    file_path = get_file_path(base_path, file_name)
    logger.info(f"Resolved file path: {file_path}")

    # Persist execution log (success so far)
    output_json = {"api_response": response_json, "file_path": file_path}
    log_genrocket_service_execution(
        db=db,
        tool_id=service.tool_id,
        tool_name="GenRocket",
        workflow_id=workflow_id,
        start_time=start_time,
        end_time=end_time,
        runtime=runtime,
        created_by=service.username,
        status="SUCCESS",
        output_json=str(output_json),
    )

    # If execution succeeded but file wasn't downloaded/found → clear message
    if not file_path or not isinstance(file_path, str) or not os.path.exists(file_path):
        raise HTTPException(
            status_code=404,
            detail="Execution completed, but output file was not downloaded"
        )

    # Stream with headers (optional success message via header)
    def iterfile():
        with open(file_path, mode="rb") as f:
            yield from f

    content_type = _guess_mime_type(file_name)
    headers = {
        "Content-Disposition": f'attachment; filename="{os.path.basename(file_name)}"',
        "X-Execution-Message": "Execution successful"  # optional for UI
    }

    return StreamingResponse(iterfile(), media_type=content_type, headers=headers)

# ---------------------- Status-only endpoint (JSON) -------------------------

@router.post("/execute-genrocket-service/{workflow_id}/status")
def execute_genrocket_service_status(
    workflow_id: int,
    x_user_id: str = Header(..., description="User ID for authentication"),
    db: Session = Depends(get_db),
):
    """
    Executes the workflow and returns only a minimal JSON status (no streaming).
    Returns:
      - 404: Workflow not found or execution completed but file not downloaded
      - 400: Scenario failed / corrupted .grs / missing filename
      - 415: Unsupported File format
      - 200 OK: Execution successful
    """
    logger.info(f"Starting GenRocket execution (status only) for workflow_id={workflow_id}")

    # 1) Workflow existence
    service = get_service_by_workflow_id(db, workflow_id)
    if not service:
        raise HTTPException(status_code=404, detail="Service not found")

    # 2) Prepare payload
    payload = execution_method_schema.Genrocket_mirror_payload(
        username=service.username,
        password=service.password,
        clientAppId=service.clientappid,
        clientUserId=service.clientuserid,
        scenario=service.scenario,
        scenarioPath=service.scenariopath,
        keepFileName=service.keepfilename
    ).dict()

    # 3) Execute GenRocket
    start_time = datetime.utcnow()
    try:
        response = requests.post(
            "http://10.100.242.133:8088/rest/scenario",
            json=payload,
            timeout=600
        )
        response.raise_for_status()
        try:
            response_json = _safe_parse_json(response)
        except HTTPException as he:
            # Corrupted .grs / invalid response
            return _log_and_return_json_failure(
                db=db,
                service=service,
                workflow_id=workflow_id,
                start_time=start_time,
                end_time=datetime.utcnow(),
                runtime=datetime.utcnow() - start_time,
                status_message=he.detail,  # "The GenRocket file is not correct"
                output_json={"payload": payload, "error": he.detail},
                http_status=400,
            )
        status = "SUCCESS"
        logger.info(f"GenRocket API response parsed successfully")
    except requests.exceptions.RequestException as e:
        status = "FAILED"
        response_json = {"error": str(e)}
        logger.error(f"GenRocket API call failed: {e}")

    end_time = datetime.utcnow()
    runtime = end_time - start_time

    # 4) Scenario failed outright
    if status != "SUCCESS":
        return JSONResponse(status_code=400, content={"code": "400", "message": "Scenario Failed"})

    # 5) Extract + validate filename
    scenario_name = service.scenario or ""
    raw_file_name = _extract_filename(response_json, scenario_name)
    try:
        file_name = _validate_filename_or_raise(raw_file_name)
    except HTTPException as he:
        return JSONResponse(status_code=he.status_code, content={"code": str(he.status_code), "message": he.detail})

    # 6) Check file presence (explicit requirement)
    base_path = r"C:\Shared_Folder\02 Tools\Genrocket Output"
    file_path = get_file_path(base_path, file_name) if file_name else None

    # Log execution regardless
    output_json = {"api_response": response_json, "file_path": file_path}
    log_genrocket_service_execution(
        db=db,
        tool_id=service.tool_id,
        tool_name="GenRocket",
        workflow_id=workflow_id,
        start_time=start_time,
        end_time=end_time,
        runtime=runtime,
        created_by=service.username,
        status="SUCCESS",
        output_json=str(output_json),
    )

    if not file_path or not isinstance(file_path, str) or not os.path.exists(file_path):
        # Clear message instead of generic 500
        raise HTTPException(
            status_code=404,
            detail="Execution completed, but output file was not downloaded"
        )

    # ✅ Success response exactly as requested
    return JSONResponse(status_code=200, content={"code": "200 OK", "message": "Execution successful"})
